### ISSUE TITLE
BE: Sleep not returning accurate "total" for the activity

### ISSUE THREAD

**Issue by jjwyse** [jjwyse/swill#91]
## Description
Response from `GET /api/v1/activities`:
```
[{
"id":"7a7c2f10-14ed-431c-ab63-29b9631b4173",
"activity_type":"sleep",
"date":"2018-12-08",
"created_at":"2018-12-08T20:13:09.719Z",
"updated_at":"2018-12-08T20:13:09.719Z",
"user_id":"29ab2a14-e0cd-42df-8911-5026e1da24e9",
"properties":[
  {
    "property_key":"minutes",
    "property_value":0,
    "total":0.0 // THIS IS WRONG
  }
],
"total":8.0
}]
```

**Comment by jjwyse** [comment]
bug is in the `Activity#calculate_total_for_property` last line, where we multiply the `property_value` by the multiplier ...

**Comment by laurawyse** [comment]
Working as expected, no changes needed.

This change doesn't make sense because sleep and food both have a start of 8 and you can only earn negative points. Therefore you actually earned 0 points by going to bed at 10, you just got 8 by default to start so the property total is accurate. It makes even less sense for food where if we made this change it could show something like:
 ```
7pts for yellow
8pts for green
6pts for red
5pts overall
``` 
This is very confusing. Instead it will show (as it does now): 
```
-1 for yellow
0 for green
-2 for red
5 overall
```
